return {
  -- {
  --   "epwalsh/obsidian.nvim",
  --   version = "*",
  --   lazy = true,
  --   ft = "markdown",
  --   dependencies = { "nvim-lua/plenary.nvim" },
  --   opts = {
  --     workspaces = {
  --       {
  --         name = "vault",
  --         path = "~/personal/vault",
  --       },
  --     },
  --   },
  -- },
  -- {
  --   "hisbaan/dataview.nvim",
  --   -- only load dataview.nvim for files in your obsidian vault
  --   event = {
  --     "BufEnter " .. vim.fn.expand("~") .. "/personal/vault/**",
  --   },
  --   -- configuration here, see below for full configuration options
  --   opts = {
  --     vault_dir = "~/personal/vault",
  --     buffer_type = "float", -- float | split | vsplit | tab
  --   },
  -- },
}
